<?php

function helloworld_menu() {
  $items = array();

  $items['helloworld'] = array(
    'title' => 'Hello World',
    'access callback' => TRUE,
    'page callback' => 'helloworld_hello_page',
    'type' => MENU_NORMAL_ITEM,
    'menu' => 'navigation',
  );

  return $items;
}


function helloworld_hello_page() {
  return t('Hello Every one');
}


/*function mymodule_menu() {
    $items = array();

    $items['my_module/hello_world'] = array(
        'title' => 'Hello World Test',
        'page callback' => 'say_hello_world',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
     );

    return $items;
}

function say_hello_world() {
    $vars = array();
    $vars['type']="ul";
    $vars['title'] = "";
    $vars['attributes']=array("");
    $vars['items'][0]="This is a simple proof of concept module";

    return theme_item_list($vars);
}
*/
/*function hello_init(){
  drupal_set_message('Hello_chethan');
}

function hello_menu(){
    $items = array();
    $$items['hello_world'] = array(
        'title' => 'Hello',
        'description' => 'Hello User',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('hello_showHelloForm'),
        'access callback' => 'user_access',
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM
    );
    return $items;
}


function hello(){
    return "Hello";
} */